{"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StoreLocatorButtonVM","kind":"identifier"}],"modules":[{"name":"MealziOSSDK"}],"roleHeading":"Class","role":"symbol","title":"StoreLocatorButtonVM","symbolKind":"class","platforms":[{"name":"iOS","unavailable":false,"introducedAt":"14.0","beta":false,"deprecated":false}],"externalID":"c:@M@MealziOSSDK@objc(cs)StoreLocatorButtonVM","navigatorTitle":[{"kind":"identifier","text":"StoreLocatorButtonVM"}]},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)MealzcoreStoreLocatorButtonViewModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/mealz.MealziOSSDK\/7Combine16ObservableObjectP","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCopying","doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","doc:\/\/mealz.MealziOSSDK\/SQ","doc:\/\/mealz.MealziOSSDK\/SH","doc:\/\/mealz.MealziOSSDK\/objc(pl)MealzcoreIExecutorScope","doc:\/\/mealz.MealziOSSDK\/objc(pl)MealzcoreKotlinx_coroutines_coreCoroutineScope"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StoreLocatorButtonVM","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/mealziossdk\/storelocatorbuttonvm"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mealziossdk\/storelocatorbuttonvm"]}],"topicSections":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM\/init()"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM\/ObservableObject-Implementations"]}],"sections":[],"identifier":{"url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://mealz.MealziOSSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/StoreLocatorButtonVM/init()":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"role":"symbol","title":"init()","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM\/init()","url":"\/documentation\/mealziossdk\/storelocatorbuttonvm\/init()"},"doc://mealz.MealziOSSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/StoreLocatorButtonVM/ObservableObject-Implementations":{"kind":"article","abstract":[],"type":"topic","role":"collectionGroup","title":"ObservableObject Implementations","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM\/ObservableObject-Implementations","url":"\/documentation\/mealziossdk\/storelocatorbuttonvm\/observableobject-implementations"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"title":"MealziOSSDK","url":"\/documentation\/mealziossdk","type":"topic","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","role":"collection","abstract":[],"kind":"symbol"},"doc://mealz.MealziOSSDK/objc(pl)MealzcoreKotlinx_coroutines_coreCoroutineScope":{"title":"mealzcore.Kotlinx_coroutines_coreCoroutineScope","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)MealzcoreKotlinx_coroutines_coreCoroutineScope","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)NSCopying":{"title":"Foundation.NSCopying","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://mealz.MealziOSSDK/objc(pl)MealzcoreIExecutorScope":{"title":"mealzcore.IExecutorScope","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(pl)MealzcoreIExecutorScope","type":"unresolvable"},"doc://mealz.MealziOSSDK/7Combine16ObservableObjectP":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/7Combine16ObservableObjectP","title":"Combine.ObservableObject"},"doc://mealz.MealziOSSDK/objc(cs)MealzcoreStoreLocatorButtonViewModel":{"type":"unresolvable","identifier":"doc:\/\/mealz.MealziOSSDK\/objc(cs)MealzcoreStoreLocatorButtonViewModel","title":"MealzcoreStoreLocatorButtonViewModel"},"doc://mealz.MealziOSSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/mealz.MealziOSSDK\/SQ","type":"unresolvable"},"doc://mealz.MealziOSSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/mealz.MealziOSSDK\/s7CVarArgP","type":"unresolvable"},"doc://mealz.MealziOSSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/mealz.MealziOSSDK\/SH","type":"unresolvable"},"doc://mealz.MealziOSSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/mealz.MealziOSSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/StoreLocatorButtonVM":{"kind":"symbol","navigatorTitle":[{"text":"StoreLocatorButtonVM","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StoreLocatorButtonVM"}],"role":"symbol","title":"StoreLocatorButtonVM","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM","url":"\/documentation\/mealziossdk\/storelocatorbuttonvm"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"replace","value":[]},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"StoreLocatorButtonVM","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"StoreLocatorButtonVM","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"StoreLocatorButtonVM"}]},{"value":[{"identifiers":["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM\/init()"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/mealz.MealziOSSDK\/objc(cs)MealzcoreStoreLocatorButtonViewModel"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"StoreLocatorButtonVM","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MealzcoreStoreLocatorButtonViewModel","text":"MealzcoreStoreLocatorButtonViewModel"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"init","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1StoreLocatorButtonVM~1init()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1StoreLocatorButtonVM~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1StoreLocatorButtonVM\/title","value":"StoreLocatorButtonVM"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1StoreLocatorButtonVM\/fragments","value":[{"text":"StoreLocatorButtonVM","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}